blog_application/blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

blog_application/blog/main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.index,name = 'index'),
    path('article/<int:pk>', views.article, name = 'get_article'),
    path('author/<int:pk>', views.author, name = 'get_author'),
    path('article', views.create_article, name = 'create_article'),
]

blog_application/blog/main/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
	name = models.CharField(max_length = 256)
	def __str__(self):
		return self.name

class Article(models.Model):
	title = models.CharField(max_length = 256)
	content = models.TextField(max_length = 256)
	created_at = models.DateTimeField(auto_now_add = True)
	# In this author is not a list...it is a relationship manager
	# use ```author.all()```
	authors = models.ManyToManyField('Author')
	
	def __str__(self):
		return self.title

blog_application/blog/main/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from main import models
# Create your views here.

def index(requests):
	# latest_articles = models.Article.objects.all()[:10]
	latest_articles = models.Article.objects.all().order_by('-created_at')[:10]
	context = {'latest_articles' : latest_articles}
	return render(requests,'main/index.html',context)

def article(requests,pk):
	# try:
	# 	article = models.Article.objects.get(id = pk)
	# except:
	# 	raise Http404()
	article = get_object_or_404(models.Article, id=pk)
	context = {'article' : article}
	return render(requests,'main/article.html',context)

def author(requests,pk):
	author = get_object_or_404(models.Author, id=pk)
	context = {'author' : author}
	return render(requests,'main/author.html',context)

def create_article(requests):
	authors = models.Author.objects.all()
	context={'authors' : authors}
	if requests.method == "POST":
		article_data = {
		"title" : requests.POST["title"],
		"content" : requests.POST["content"]
		}
		print("Content:"+requests.POST["content"])
		article = models.Article.objects.create(**article_data)
		author = models.Author.objects.get(pk = requests.POST["author"])
		article.authors.set([author])
		# author = models.Author.objects.filter(pk = requests.POST["author"])
		# article.authors.set(author)
		context["success"] = True
	
	response = render(requests,'main/create_article.html',context)
	return response

blog_application/blog/templates/main/article.html
{% extends 'main/base.html' %}


{% block content %}

<h1>Title: {{article.title}}</h1>
<h3>Created At: {{article.created_at}}</h3>
<h4>Written By:
	{% for author in article.author.all %}
	<a href="{% url 'get_author' author.pk %}">{{author}},</a>
	{% endfor %}

 </h4>

<p>
	{{ article.content }}
</p>

{% endblock %}

blog_application/blog/templates/main/author.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Author Name: {{author.name}}</h5>
<h4>
Articles: 
{% for article in author.article_set.all %}
<a href="{% url 'get_article' article.pk %}">{{article}},</a>
{% endfor %}
</h4>

{% endblock %}

blog_application/blog/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Blog Application</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

blog_application/blog/templates/main/create_article.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Create Article</h1>
{% if success %}
<p>Form submitted successfully!!</p>
{% endif %}

<form method="POST">
	{% csrf_token %}
	<input type="text" name="title" placeholder="Title">
	<textarea name="content" placeholder="Content"></textarea>
	<select name="author">
		{% for author in authors %}
		<option value="{{author.pk}}">{{author.name}}</option>
		{% endfor %}
	</select>
	<button type="submit">Submit</button>
	<button type="reset">Reset</button>
</form>
{% endblock %}

blog_application/blog/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Welcome to blog application</h1>

<h5>Top 10 aticles!!</h5>
<ul>
	{% for article in latest_articles %}
	<li>
		<a href="{% url 'get_article' article.pk %}">{{article.title}}</a>
	</li>
	{% endfor %}

</ul>


{% endblock %}